-- XAUTH_APPLICATION
CREATE TABLE PCRFMGR.XAUTH_APPLICATION (
	APP_ID			VARCHAR2(30 CHAR)		NOT NULL,
	APP_NAME		VARCHAR2(150 CHAR)		NOT NULL,
	ENABLED		    VARCHAR2(1 CHAR)		DEFAULT '1' NOT NULL,
	PUBLIC_KEY		VARCHAR2(1500 CHAR)		NOT NULL,
	PRIVATE_KEY		VARCHAR2(1500 CHAR)		NOT NULL,
	CRE_USER        VARCHAR2(50 CHAR)       NOT NULL,
	CRE_DATE        DATE           			NOT NULL,
	UPD_USER        VARCHAR2(50 CHAR),
	UPD_DATE        DATE
);

COMMENT ON TABLE PCRFMGR.XAUTH_APPLICATION IS '系統資料檔';

COMMENT ON COLUMN PCRFMGR.XAUTH_APPLICATION.APP_ID IS '系統代號';

COMMENT ON COLUMN PCRFMGR.XAUTH_APPLICATION.APP_NAME IS '系統名稱';

COMMENT ON COLUMN PCRFMGR.XAUTH_APPLICATION.ENABLED IS '是否啟用 0:停用 1:啟用';

COMMENT ON COLUMN PCRFMGR.XAUTH_APPLICATION.PUBLIC_KEY IS '公鑰';

COMMENT ON COLUMN PCRFMGR.XAUTH_APPLICATION.PRIVATE_KEY IS '私鑰';

COMMENT ON COLUMN PCRFMGR.XAUTH_APPLICATION.CRE_USER IS '建立人員';

COMMENT ON COLUMN PCRFMGR.XAUTH_APPLICATION.CRE_DATE IS '建立日期';

COMMENT ON COLUMN PCRFMGR.XAUTH_APPLICATION.UPD_USER IS '異動人員';

COMMENT ON COLUMN PCRFMGR.XAUTH_APPLICATION.UPD_DATE IS '異動日期';

CREATE UNIQUE INDEX PCRFMGR.XAUTH_APPLICATION_PK ON PCRFMGR.XAUTH_APPLICATION
(APP_ID);

ALTER TABLE PCRFMGR.XAUTH_APPLICATION ADD (
  CONSTRAINT XAUTH_APPLICATION_PK
  PRIMARY KEY
  (APP_ID)
  USING INDEX PCRFMGR.XAUTH_APPLICATION_PK
  ENABLE VALIDATE);
  
-- XAUTH_DEPT
CREATE TABLE PCRFMGR.XAUTH_DEPT (
	APP_ID			VARCHAR2(30 CHAR)			NOT NULL,
	IDEN_ID         VARCHAR2(20 CHAR)           NOT NULL,  
	BAN				VARCHAR2(10 CHAR),
	CNAME			VARCHAR2(150 CHAR)			NOT NULL,
	PARENT_ID		VARCHAR2(20 CHAR)			NOT NULL,
	SEQ_NO		    NUMBER						NOT NULL,
	PARENT_SEQ	    NUMBER						NOT NULL,
	ENABLED		    VARCHAR2(1 CHAR)			DEFAULT '1' NOT NULL,
	CRE_USER        VARCHAR2(50 CHAR)           NOT NULL,
	CRE_DATE        DATE                        NOT NULL,
	UPD_USER        VARCHAR2(50 CHAR),
	UPD_DATE        DATE
);

COMMENT ON TABLE PCRFMGR.XAUTH_DEPT IS '部門資料檔';

COMMENT ON COLUMN PCRFMGR.XAUTH_DEPT.APP_ID IS '系統代號';

COMMENT ON COLUMN PCRFMGR.XAUTH_DEPT.IDEN_ID IS '識別碼';

COMMENT ON COLUMN PCRFMGR.XAUTH_DEPT.BAN IS '統一編號';

COMMENT ON COLUMN PCRFMGR.XAUTH_DEPT.CNAME IS '部門名稱';

COMMENT ON COLUMN PCRFMGR.XAUTH_DEPT.PARENT_ID IS '上層選單編號';

COMMENT ON COLUMN PCRFMGR.XAUTH_DEPT.SEQ_NO IS '顯示順序';

COMMENT ON COLUMN PCRFMGR.XAUTH_DEPT.PARENT_SEQ IS '上層順序';

COMMENT ON COLUMN PCRFMGR.XAUTH_DEPT.ENABLED IS '是否啟用';

COMMENT ON COLUMN PCRFMGR.XAUTH_DEPT.CRE_USER IS '建立人員';

COMMENT ON COLUMN PCRFMGR.XAUTH_DEPT.CRE_DATE IS '建立日期';

COMMENT ON COLUMN PCRFMGR.XAUTH_DEPT.UPD_USER IS '異動人員';

COMMENT ON COLUMN PCRFMGR.XAUTH_DEPT.UPD_DATE IS '異動日期';

CREATE UNIQUE INDEX PCRFMGR.XAUTH_DEPT_PK ON PCRFMGR.XAUTH_DEPT
(APP_ID, IDEN_ID);  

ALTER TABLE PCRFMGR.XAUTH_DEPT ADD (
  CONSTRAINT XAUTH_DEPT_PK
  PRIMARY KEY
  (APP_ID, IDEN_ID)
  USING INDEX PCRFMGR.XAUTH_DEPT_PK
  ENABLE VALIDATE);

  
-- XAUTH_IDEN_MENU
CREATE TABLE PCRFMGR.XAUTH_IDEN_MENU
(  
	APP_ID				VARCHAR2(30 CHAR)			NOT NULL,
	IDEN_ID          	VARCHAR2(20 CHAR)           NOT NULL,
	MENU_ID	       	 	VARCHAR2(40 CHAR)			NOT NULL,
	CRE_USER         	VARCHAR2(50 CHAR)           NOT NULL,
	CRE_DATE         	DATE                        NOT NULL,
	UPD_USER         	VARCHAR2(50 CHAR),
	UPD_DATE         	DATE                         
);

COMMENT ON TABLE PCRFMGR.XAUTH_IDEN_MENU IS '識別選單資料檔';

COMMENT ON COLUMN PCRFMGR.XAUTH_IDEN_MENU.APP_ID IS '系統代號';

COMMENT ON COLUMN PCRFMGR.XAUTH_IDEN_MENU.IDEN_ID IS '識別碼';

COMMENT ON COLUMN PCRFMGR.XAUTH_IDEN_MENU.MENU_ID IS '選單編號';

COMMENT ON COLUMN PCRFMGR.XAUTH_IDEN_MENU.CRE_USER IS '建立人員';

COMMENT ON COLUMN PCRFMGR.XAUTH_IDEN_MENU.CRE_DATE IS '建立日期';

COMMENT ON COLUMN PCRFMGR.XAUTH_IDEN_MENU.UPD_USER IS '異動人員';

COMMENT ON COLUMN PCRFMGR.XAUTH_IDEN_MENU.UPD_DATE IS '異動日期';

CREATE UNIQUE INDEX PCRFMGR.XAUTH_IDEN_MENU_PK ON PCRFMGR.XAUTH_IDEN_MENU
(APP_ID, IDEN_ID, MENU_ID);


ALTER TABLE PCRFMGR.XAUTH_IDEN_MENU ADD (
  CONSTRAINT XAUTH_IDEN_MENU_PK
  PRIMARY KEY
  (APP_ID, IDEN_ID, MENU_ID)
  USING INDEX PCRFMGR.XAUTH_IDEN_MENU_PK
  ENABLE VALIDATE);
  
  
-- XAUTH_MENU
CREATE TABLE PCRFMGR.XAUTH_MENU
(
	APP_ID				VARCHAR2(30 CHAR)			NOT NULL,
	MENU_ID	       		VARCHAR2(40 CHAR)			NOT NULL,
	MENU_URL	        VARCHAR2(150 CHAR),
	MENU_CNAME	   		VARCHAR2(150 CHAR)			NOT NULL,
	PARENT_ID		    VARCHAR2(20 CHAR)			NOT NULL,
	SEQ_NO		   		NUMBER						NOT NULL,
	PARENT_SEQ	   		NUMBER						NOT NULL,
	MEMO			   	VARCHAR2(150 CHAR),
	CRE_USER         	VARCHAR2(50 CHAR)           NOT NULL,
	CRE_DATE         	DATE                        NOT NULL,
	UPD_USER         	VARCHAR2(50 CHAR),
	UPD_DATE         	DATE                         
);

COMMENT ON TABLE PCRFMGR.XAUTH_MENU IS '選單資料檔';

COMMENT ON COLUMN PCRFMGR.XAUTH_MENU.APP_ID IS '系統代號';

COMMENT ON COLUMN PCRFMGR.XAUTH_MENU.MENU_ID IS '選單編號';

COMMENT ON COLUMN PCRFMGR.XAUTH_MENU.MENU_URL IS '選單網址';

COMMENT ON COLUMN PCRFMGR.XAUTH_MENU.MENU_CNAME IS '選單名稱';

COMMENT ON COLUMN PCRFMGR.XAUTH_MENU.PARENT_ID IS '上層選單編號';

COMMENT ON COLUMN PCRFMGR.XAUTH_MENU.SEQ_NO IS '顯示順序';

COMMENT ON COLUMN PCRFMGR.XAUTH_MENU.PARENT_SEQ IS '上層順序';

COMMENT ON COLUMN PCRFMGR.XAUTH_MENU.MEMO IS '備註';

COMMENT ON COLUMN PCRFMGR.XAUTH_MENU.CRE_USER IS '建立人員';

COMMENT ON COLUMN PCRFMGR.XAUTH_MENU.CRE_DATE IS '建立日期';

COMMENT ON COLUMN PCRFMGR.XAUTH_MENU.UPD_USER IS '異動人員';

COMMENT ON COLUMN PCRFMGR.XAUTH_MENU.UPD_DATE IS '異動日期';

CREATE UNIQUE INDEX PCRFMGR.XAUTH_MENU_PK ON PCRFMGR.XAUTH_MENU
(APP_ID, MENU_ID);

CREATE INDEX PCRFMGR.XAUTH_MENU_IDX01 ON PCRFMGR.XAUTH_MENU
(APP_ID, MENU_URL);


ALTER TABLE PCRFMGR.XAUTH_MENU ADD (
  CONSTRAINT XAUTH_MENU_PK
  PRIMARY KEY
  (APP_ID, MENU_ID)
  USING INDEX PCRFMGR.XAUTH_MENU_PK
  ENABLE VALIDATE);

 
-- XAUTH_ROLE
CREATE TABLE PCRFMGR.XAUTH_ROLE
(
	APP_ID				VARCHAR2(30 CHAR)			NOT NULL,
	IDEN_ID          	VARCHAR2(20 CHAR)           NOT NULL,
	ROLE_ID          	VARCHAR2(20 CHAR)           NOT NULL,
	ROLE_CNAME       	VARCHAR2(150 CHAR)          NOT NULL,
	CRE_USER         	VARCHAR2(50 CHAR)           NOT NULL,
	CRE_DATE         	DATE                        NOT NULL,
	UPD_USER         	VARCHAR2(50 CHAR),
	UPD_DATE         	DATE                         
);

COMMENT ON TABLE PCRFMGR.XAUTH_ROLE IS '角色資料檔';

COMMENT ON COLUMN PCRFMGR.XAUTH_ROLE.APP_ID IS '系統代號';

COMMENT ON COLUMN PCRFMGR.XAUTH_ROLE.IDEN_ID IS '識別碼';

COMMENT ON COLUMN PCRFMGR.XAUTH_ROLE.ROLE_ID IS '角色代號';

COMMENT ON COLUMN PCRFMGR.XAUTH_ROLE.ROLE_CNAME IS '角色名稱';

COMMENT ON COLUMN PCRFMGR.XAUTH_ROLE.CRE_USER IS '建立人員';

COMMENT ON COLUMN PCRFMGR.XAUTH_ROLE.CRE_DATE IS '建立日期';

COMMENT ON COLUMN PCRFMGR.XAUTH_ROLE.UPD_USER IS '異動人員';

COMMENT ON COLUMN PCRFMGR.XAUTH_ROLE.UPD_DATE IS '異動日期';

CREATE UNIQUE INDEX PCRFMGR.XAUTH_ROLE_PK ON PCRFMGR.XAUTH_ROLE
(APP_ID, IDEN_ID, ROLE_ID);


ALTER TABLE PCRFMGR.XAUTH_ROLE ADD (
  CONSTRAINT XAUTH_ROLE_PK
  PRIMARY KEY
  (APP_ID, IDEN_ID, ROLE_ID)
  USING INDEX PCRFMGR.XAUTH_ROLE_PK
  ENABLE VALIDATE);


-- XAUTH_ROLE_MENU 
CREATE TABLE PCRFMGR.XAUTH_ROLE_MENU
(  
	APP_ID				VARCHAR2(30 CHAR)			NOT NULL,
	IDEN_ID          	VARCHAR2(20 CHAR)           NOT NULL,
	ROLE_ID          	VARCHAR2(20 CHAR)           NOT NULL,  
	MENU_ID	       		VARCHAR2(40 CHAR)			NOT NULL,
	CRE_USER         	VARCHAR2(50 CHAR)           NOT NULL,
	CRE_DATE         	DATE                        NOT NULL,
	UPD_USER         	VARCHAR2(50 CHAR),
	UPD_DATE         	DATE                         
);

COMMENT ON TABLE PCRFMGR.XAUTH_ROLE_MENU IS '角色選單資料檔';

COMMENT ON COLUMN PCRFMGR.XAUTH_ROLE_MENU.APP_ID IS '系統代號';

COMMENT ON COLUMN PCRFMGR.XAUTH_ROLE_MENU.MENU_ID IS '選單編號';

COMMENT ON COLUMN PCRFMGR.XAUTH_ROLE_MENU.IDEN_ID IS '識別碼';

COMMENT ON COLUMN PCRFMGR.XAUTH_ROLE_MENU.ROLE_ID IS '角色代號';

COMMENT ON COLUMN PCRFMGR.XAUTH_ROLE_MENU.CRE_USER IS '建立人員';

COMMENT ON COLUMN PCRFMGR.XAUTH_ROLE_MENU.CRE_DATE IS '建立日期';

COMMENT ON COLUMN PCRFMGR.XAUTH_ROLE_MENU.UPD_USER IS '異動人員';

COMMENT ON COLUMN PCRFMGR.XAUTH_ROLE_MENU.UPD_DATE IS '異動日期';

CREATE UNIQUE INDEX PCRFMGR.XAUTH_ROLE_MENU_PK ON PCRFMGR.XAUTH_ROLE_MENU
(APP_ID, IDEN_ID, ROLE_ID, MENU_ID);


ALTER TABLE PCRFMGR.XAUTH_ROLE_MENU ADD (
  CONSTRAINT XAUTH_ROLE_MENU_PK
  PRIMARY KEY
  (APP_ID, IDEN_ID, ROLE_ID, MENU_ID)
  USING INDEX PCRFMGR.XAUTH_ROLE_MENU_PK
  ENABLE VALIDATE);


  
-- XAUTH_ROLE_USER  
CREATE TABLE PCRFMGR.XAUTH_ROLE_USER
(
	APP_ID				VARCHAR2(30 CHAR)			NOT NULL,
	IDEN_ID          	VARCHAR2(20 CHAR)           NOT NULL,
	ROLE_ID          	VARCHAR2(20 CHAR)           NOT NULL,
	USER_ID          	VARCHAR2(30 CHAR)           NOT NULL,
	CRE_USER         	VARCHAR2(50 CHAR)           NOT NULL,
	CRE_DATE         	DATE                        NOT NULL,
	UPD_USER         	VARCHAR2(50 CHAR),
	UPD_DATE         	DATE                         
);

COMMENT ON TABLE PCRFMGR.XAUTH_ROLE_USER IS '角色與使用者對應檔';

COMMENT ON COLUMN PCRFMGR.XAUTH_ROLE_USER.APP_ID IS '系統代號';

COMMENT ON COLUMN PCRFMGR.XAUTH_ROLE_USER.IDEN_ID IS '識別碼';

COMMENT ON COLUMN PCRFMGR.XAUTH_ROLE_USER.ROLE_ID IS '角色代號';

COMMENT ON COLUMN PCRFMGR.XAUTH_ROLE_USER.USER_ID IS '使用者帳號';

COMMENT ON COLUMN PCRFMGR.XAUTH_ROLE_USER.CRE_USER IS '建立人員';

COMMENT ON COLUMN PCRFMGR.XAUTH_ROLE_USER.CRE_DATE IS '建立日期';

COMMENT ON COLUMN PCRFMGR.XAUTH_ROLE_USER.UPD_USER IS '異動人員';

COMMENT ON COLUMN PCRFMGR.XAUTH_ROLE_USER.UPD_DATE IS '異動日期';

CREATE UNIQUE INDEX PCRFMGR.XAUTH_ROLE_USER_PK ON PCRFMGR.XAUTH_ROLE_USER
(APP_ID, IDEN_ID, ROLE_ID, USER_ID);


ALTER TABLE PCRFMGR.XAUTH_ROLE_USER ADD (
  CONSTRAINT XAUTH_ROLE_USER_PK
  PRIMARY KEY
  (APP_ID, IDEN_ID, ROLE_ID, USER_ID)
  USING INDEX PCRFMGR.XAUTH_ROLE_USER_PK
  ENABLE VALIDATE);

  
-- XAUTH_USERS  
CREATE TABLE PCRFMGR.XAUTH_USERS
(
	APP_ID				VARCHAR2(30 CHAR)			NOT NULL,
	IDEN_ID          	VARCHAR2(20 CHAR)           NOT NULL,
	USER_ID          	VARCHAR2(30 CHAR)           NOT NULL,
	USER_PW          	VARCHAR2(60 CHAR)           NOT NULL,
	USER_CNAME       	VARCHAR2(60 CHAR)           NOT NULL,  
	USER_TYPE		    VARCHAR2(2 CHAR)			DEFAULT '02' NOT NULL,
	ENABLED		   		VARCHAR2(1 CHAR)			DEFAULT '1' NOT NULL,
	IS_FIRST		    VARCHAR2(1 CHAR)			DEFAULT '1' NOT NULL,
	EMAIL         		VARCHAR2(50 CHAR),
	EMAIL_TOKEN   		VARCHAR2(100 CHAR),
	EMAIL_EXPIRE  		DATE,
	CRE_USER         	VARCHAR2(50 CHAR)           NOT NULL,
	CRE_DATE         	DATE                        NOT NULL,
	UPD_USER         	VARCHAR2(50 CHAR),
	UPD_DATE         	DATE                         
);

COMMENT ON TABLE PCRFMGR.XAUTH_USERS IS '使用者資料檔';

COMMENT ON COLUMN PCRFMGR.XAUTH_USERS.APP_ID IS '系統代號';

COMMENT ON COLUMN PCRFMGR.XAUTH_USERS.IDEN_ID IS '識別碼';

COMMENT ON COLUMN PCRFMGR.XAUTH_USERS.USER_ID IS '使用者帳號';

COMMENT ON COLUMN PCRFMGR.XAUTH_USERS.USER_PW IS '使用者密碼';

COMMENT ON COLUMN PCRFMGR.XAUTH_USERS.USER_CNAME IS '使用者姓名';

COMMENT ON COLUMN PCRFMGR.XAUTH_USERS.USER_TYPE IS '使用者類型 00:系統管理員 01:管理員 02:使用者';

COMMENT ON COLUMN PCRFMGR.XAUTH_USERS.ENABLED IS '是否啟用 0:停用 1:啟用';

COMMENT ON COLUMN PCRFMGR.XAUTH_USERS.IS_FIRST IS '是否第一次登入 0:否 1:是';

COMMENT ON COLUMN PCRFMGR.XAUTH_USERS.EMAIL IS '電子郵件';

COMMENT ON COLUMN PCRFMGR.XAUTH_USERS.EMAIL_TOKEN IS '電子郵件重新認証識別碼';

COMMENT ON COLUMN PCRFMGR.XAUTH_USERS.EMAIL_EXPIRE IS '電子郵件重新認証到期日';

COMMENT ON COLUMN PCRFMGR.XAUTH_USERS.CRE_USER IS '建立人員';

COMMENT ON COLUMN PCRFMGR.XAUTH_USERS.CRE_DATE IS '建立日期';

COMMENT ON COLUMN PCRFMGR.XAUTH_USERS.UPD_USER IS '異動人員';

COMMENT ON COLUMN PCRFMGR.XAUTH_USERS.UPD_DATE IS '異動日期';

CREATE UNIQUE INDEX PCRFMGR.XAUTH_USERS_PK ON PCRFMGR.XAUTH_USERS
(APP_ID, IDEN_ID, USER_ID);


ALTER TABLE PCRFMGR.XAUTH_USERS ADD (
  CONSTRAINT XAUTH_USERS_PK
  PRIMARY KEY
  (APP_ID, IDEN_ID, USER_ID)
  USING INDEX PCRFMGR.XAUTH_USERS_PK
  ENABLE VALIDATE);
  
-- XAUTH_USERS_PWD_HISTORY
CREATE TABLE PCRFMGR.XAUTH_USERS_PWD_HISTORY
(
	APP_ID				VARCHAR2(30 CHAR)			NOT NULL,
	IDEN_ID          	VARCHAR2(20 CHAR)           NOT NULL,
	USER_ID          	VARCHAR2(30 CHAR)           NOT NULL,
	USER_PW          	VARCHAR2(60 CHAR)           NOT NULL,
	CRE_USER         	VARCHAR2(50 CHAR)           NOT NULL,
	CRE_DATE         	DATE                        NOT NULL,
	UPD_USER         	VARCHAR2(50 CHAR),
	UPD_DATE         	DATE                         
);

COMMENT ON TABLE PCRFMGR.XAUTH_USERS_PWD_HISTORY IS '使用者密碼歷史檔';

COMMENT ON COLUMN PCRFMGR.XAUTH_USERS_PWD_HISTORY.APP_ID IS '系統代號';

COMMENT ON COLUMN PCRFMGR.XAUTH_USERS_PWD_HISTORY.IDEN_ID IS '識別碼';

COMMENT ON COLUMN PCRFMGR.XAUTH_USERS_PWD_HISTORY.USER_ID IS '使用者帳號';

COMMENT ON COLUMN PCRFMGR.XAUTH_USERS_PWD_HISTORY.USER_PW IS '使用者密碼';

COMMENT ON COLUMN PCRFMGR.XAUTH_USERS_PWD_HISTORY.CRE_USER IS '建立人員';

COMMENT ON COLUMN PCRFMGR.XAUTH_USERS_PWD_HISTORY.CRE_DATE IS '建立日期';

COMMENT ON COLUMN PCRFMGR.XAUTH_USERS_PWD_HISTORY.UPD_USER IS '異動人員';

COMMENT ON COLUMN PCRFMGR.XAUTH_USERS_PWD_HISTORY.UPD_DATE IS '異動日期';

CREATE UNIQUE INDEX PCRFMGR.XAUTH_USERS_PWD_HISTORY_PK ON PCRFMGR.XAUTH_USERS_PWD_HISTORY
(APP_ID, IDEN_ID, USER_ID, CRE_DATE);


ALTER TABLE PCRFMGR.XAUTH_USERS_PWD_HISTORY ADD (
  CONSTRAINT XAUTH_USERS_PWD_HISTORY_PK
  PRIMARY KEY
  (APP_ID, IDEN_ID, USER_ID, CRE_DATE)
  USING INDEX PCRFMGR.XAUTH_USERS_PWD_HISTORY_PK
  ENABLE VALIDATE);
  
-- XAUTH_USERS_TOKEN
CREATE TABLE PCRFMGR.XAUTH_USERS_TOKEN 
(
	APP_ID				VARCHAR2(30 CHAR)			NOT NULL,
	IDEN_ID           	VARCHAR2(20 CHAR)           NOT NULL,  
	USER_ID           	VARCHAR2(30 CHAR)           NOT NULL,
	TOKEN				VARCHAR2(100 CHAR)			NOT NULL,
	ACTIVE_DATE			DATE						NOT NULL,
	CRE_USER          	VARCHAR2(50 CHAR)           NOT NULL,
	CRE_DATE          	DATE                        NOT NULL,
	UPD_USER          	VARCHAR2(50 CHAR),
	UPD_DATE          	DATE
);

COMMENT ON TABLE PCRFMGR.XAUTH_USERS_TOKEN IS '使用者登入識別檔';

COMMENT ON COLUMN PCRFMGR.XAUTH_USERS_TOKEN.APP_ID IS '系統代號';

COMMENT ON COLUMN PCRFMGR.XAUTH_USERS_TOKEN.IDEN_ID IS '識別碼';

COMMENT ON COLUMN PCRFMGR.XAUTH_USERS_TOKEN.USER_ID IS '使用者帳號';

COMMENT ON COLUMN PCRFMGR.XAUTH_USERS_TOKEN.TOKEN IS 'TOKEN';

COMMENT ON COLUMN PCRFMGR.XAUTH_USERS_TOKEN.ACTIVE_DATE IS '啟用日期';

COMMENT ON COLUMN PCRFMGR.XAUTH_USERS_TOKEN.CRE_USER IS '建立人員';

COMMENT ON COLUMN PCRFMGR.XAUTH_USERS_TOKEN.CRE_DATE IS '建立日期';

COMMENT ON COLUMN PCRFMGR.XAUTH_USERS_TOKEN.UPD_USER IS '異動人員';

COMMENT ON COLUMN PCRFMGR.XAUTH_USERS_TOKEN.UPD_DATE IS '異動日期';

CREATE UNIQUE INDEX PCRFMGR.XAUTH_USERS_TOKEN_PK ON PCRFMGR.XAUTH_USERS_TOKEN
(APP_ID, IDEN_ID, USER_ID);


ALTER TABLE PCRFMGR.XAUTH_USERS_TOKEN ADD (
  CONSTRAINT XAUTH_USERS_TOKEN_PK
  PRIMARY KEY
  (APP_ID, IDEN_ID, USER_ID)
  USING INDEX PCRFMGR.XAUTH_USERS_TOKEN_PK
  ENABLE VALIDATE);  
  
-- XAUTH_IP_GRANT  
CREATE TABLE PCRFMGR.XAUTH_IP_GRANT
(
	APP_ID				VARCHAR2(30 CHAR)					NOT NULL,
	IDEN_ID    			VARCHAR2(20 CHAR)                   NOT NULL,
	IP_ADDR	        	VARCHAR2(50 CHAR) 					NOT NULL,
	SYS_TYPE			VARCHAR2(20 CHAR)					NOT NULL,
	ENABLED    			VARCHAR2(1 CHAR)                    DEFAULT '1' NOT NULL,	
	MEMO			   	VARCHAR2(150 CHAR),
	CRE_USER         	VARCHAR2(50 CHAR)           		NOT NULL,
	CRE_DATE         	DATE                        		NOT NULL,
	UPD_USER         	VARCHAR2(50 CHAR),
	UPD_DATE         	DATE                         
);

COMMENT ON TABLE PCRFMGR.XAUTH_IP_GRANT IS 'IP授權資料檔';

COMMENT ON COLUMN PCRFMGR.XAUTH_IP_GRANT.APP_ID IS '系統代號';

COMMENT ON COLUMN PCRFMGR.XAUTH_IP_GRANT.IDEN_ID IS '識別碼';

COMMENT ON COLUMN PCRFMGR.XAUTH_IP_GRANT.IP_ADDR IS '網路IP位址';

COMMENT ON COLUMN PCRFMGR.XAUTH_IP_GRANT.SYS_TYPE IS '系統別 REF:XAUTH_SYS_CODE.GP';

COMMENT ON COLUMN PCRFMGR.XAUTH_IP_GRANT.ENABLED IS '是否啟用 0:停用 1:啟用';

COMMENT ON COLUMN PCRFMGR.XAUTH_IP_GRANT.MEMO IS '備註';

COMMENT ON COLUMN PCRFMGR.XAUTH_IP_GRANT.CRE_USER IS '建立人員';

COMMENT ON COLUMN PCRFMGR.XAUTH_IP_GRANT.CRE_DATE IS '建立日期';

COMMENT ON COLUMN PCRFMGR.XAUTH_IP_GRANT.UPD_USER IS '異動人員';

COMMENT ON COLUMN PCRFMGR.XAUTH_IP_GRANT.UPD_DATE IS '異動日期';

CREATE UNIQUE INDEX PCRFMGR.XAUTH_IP_GRANT_PK ON PCRFMGR.XAUTH_IP_GRANT
(APP_ID, IDEN_ID, IP_ADDR, SYS_TYPE);


ALTER TABLE PCRFMGR.XAUTH_IP_GRANT ADD (
  CONSTRAINT XAUTH_IP_GRANT_PK
  PRIMARY KEY
  (APP_ID, IDEN_ID, IP_ADDR, SYS_TYPE)
  USING INDEX PCRFMGR.XAUTH_IP_GRANT_PK
  ENABLE VALIDATE);
  
-- XAUTH_SYS_CODE 
CREATE TABLE PCRFMGR.XAUTH_SYS_CODE
(
	APP_ID				VARCHAR2(30 CHAR)			NOT NULL,
	IDEN_ID    			VARCHAR2(20 CHAR)           NOT NULL,
	GP         			VARCHAR2(20 CHAR)           NOT NULL,
	CODE       			VARCHAR2(15 CHAR)           NOT NULL,
	CNAME      			VARCHAR2(150 CHAR)          NOT NULL,
	ENAME      			VARCHAR2(150 CHAR),
	ORDER_SEQ  			NUMBER,
	ENABLED    			VARCHAR2(1 CHAR)            DEFAULT '1' NOT NULL,
	BGN_DATE   			DATE                        NOT NULL,
	END_DATE   			DATE,
	MEMO       			VARCHAR2(150 CHAR),
	C01        			VARCHAR2(150 CHAR),
	C02        			VARCHAR2(150 CHAR),
	C03        			VARCHAR2(150 CHAR),
	C04        			VARCHAR2(150 CHAR),
	C05        			VARCHAR2(150 CHAR),
	CRE_USER   			VARCHAR2(50 CHAR)           NOT NULL,
	CRE_DATE   			DATE                        NOT NULL,
	UPD_USER   			VARCHAR2(50 CHAR),
	UPD_DATE   			DATE
);

COMMENT ON TABLE PCRFMGR.XAUTH_SYS_CODE IS '系統代碼檔';

COMMENT ON COLUMN PCRFMGR.XAUTH_SYS_CODE.APP_ID IS '系統代號';

COMMENT ON COLUMN PCRFMGR.XAUTH_SYS_CODE.IDEN_ID IS '識別碼';

COMMENT ON COLUMN PCRFMGR.XAUTH_SYS_CODE.GP IS '群組';

COMMENT ON COLUMN PCRFMGR.XAUTH_SYS_CODE.CODE IS '代碼';

COMMENT ON COLUMN PCRFMGR.XAUTH_SYS_CODE.CNAME IS '中文名稱';

COMMENT ON COLUMN PCRFMGR.XAUTH_SYS_CODE.ENAME IS '英文名稱';

COMMENT ON COLUMN PCRFMGR.XAUTH_SYS_CODE.ORDER_SEQ IS '顯示順序';

COMMENT ON COLUMN PCRFMGR.XAUTH_SYS_CODE.ENABLED IS '是否啟用 0:停用 1:啟用';

COMMENT ON COLUMN PCRFMGR.XAUTH_SYS_CODE.BGN_DATE IS '起始日期';

COMMENT ON COLUMN PCRFMGR.XAUTH_SYS_CODE.END_DATE IS '截止日期';

COMMENT ON COLUMN PCRFMGR.XAUTH_SYS_CODE.MEMO IS '備註';

COMMENT ON COLUMN PCRFMGR.XAUTH_SYS_CODE.C01 IS '擴充欄位1';

COMMENT ON COLUMN PCRFMGR.XAUTH_SYS_CODE.C02 IS '擴充欄位2';

COMMENT ON COLUMN PCRFMGR.XAUTH_SYS_CODE.C03 IS '擴充欄位3';

COMMENT ON COLUMN PCRFMGR.XAUTH_SYS_CODE.C04 IS '擴充欄位4';

COMMENT ON COLUMN PCRFMGR.XAUTH_SYS_CODE.C05 IS '擴充欄位5';

COMMENT ON COLUMN PCRFMGR.XAUTH_SYS_CODE.CRE_USER IS '建立人員';

COMMENT ON COLUMN PCRFMGR.XAUTH_SYS_CODE.CRE_DATE IS '建立日期';

COMMENT ON COLUMN PCRFMGR.XAUTH_SYS_CODE.UPD_USER IS '異動人員';

COMMENT ON COLUMN PCRFMGR.XAUTH_SYS_CODE.UPD_DATE IS '異動日期';


CREATE UNIQUE INDEX PCRFMGR.XAUTH_SYS_CODE_PK ON PCRFMGR.XAUTH_SYS_CODE
(APP_ID, IDEN_ID, GP, CODE);


ALTER TABLE PCRFMGR.XAUTH_SYS_CODE ADD (
  CONSTRAINT XAUTH_SYS_CODE_PK
  PRIMARY KEY
  (APP_ID, IDEN_ID, GP, CODE)
  USING INDEX PCRFMGR.XAUTH_SYS_CODE_PK
  ENABLE VALIDATE);
  
-- XAUTH_USERS_SECRET
CREATE TABLE PCRFMGR.XAUTH_USERS_SECRET
(  
	APP_ID				VARCHAR2(30 CHAR)			NOT NULL,
	IDEN_ID          	VARCHAR2(20 CHAR)           NOT NULL,
	USER_ID	       	 	VARCHAR2(30 CHAR)			NOT NULL,
	TOKEN	       	 	VARCHAR2(300 CHAR)			NOT NULL,
	EXPIRE_DATE	       	DATE						NOT NULL,
	PUBLIC_KEY	       	VARCHAR2(1500 CHAR)			NOT NULL,
	PRIVATE_KEY	       	VARCHAR2(1500 CHAR)			NOT NULL,
	CRE_USER         	VARCHAR2(50 CHAR)           NOT NULL,
	CRE_DATE         	DATE                        NOT NULL,
	UPD_USER         	VARCHAR2(50 CHAR),
	UPD_DATE         	DATE                         
);

COMMENT ON TABLE PCRFMGR.XAUTH_USERS_SECRET IS '使用者密鑰檔';

COMMENT ON COLUMN PCRFMGR.XAUTH_USERS_SECRET.APP_ID IS '系統代號';

COMMENT ON COLUMN PCRFMGR.XAUTH_USERS_SECRET.IDEN_ID IS '識別碼';

COMMENT ON COLUMN PCRFMGR.XAUTH_USERS_SECRET.USER_ID IS '使用者帳號';

COMMENT ON COLUMN PCRFMGR.XAUTH_USERS_SECRET.TOKEN IS 'TOKEN';

COMMENT ON COLUMN PCRFMGR.XAUTH_USERS_SECRET.EXPIRE_DATE IS '到期日期';

COMMENT ON COLUMN PCRFMGR.XAUTH_USERS_SECRET.PUBLIC_KEY IS '公鑰';

COMMENT ON COLUMN PCRFMGR.XAUTH_USERS_SECRET.PRIVATE_KEY IS '私鑰';

COMMENT ON COLUMN PCRFMGR.XAUTH_USERS_SECRET.CRE_USER IS '建立人員';

COMMENT ON COLUMN PCRFMGR.XAUTH_USERS_SECRET.CRE_DATE IS '建立日期';

COMMENT ON COLUMN PCRFMGR.XAUTH_USERS_SECRET.UPD_USER IS '異動人員';

COMMENT ON COLUMN PCRFMGR.XAUTH_USERS_SECRET.UPD_DATE IS '異動日期';

CREATE UNIQUE INDEX PCRFMGR.XAUTH_USERS_SECRET_PK ON PCRFMGR.XAUTH_USERS_SECRET
(APP_ID, IDEN_ID, USER_ID);


ALTER TABLE PCRFMGR.XAUTH_USERS_SECRET ADD (
  CONSTRAINT XAUTH_USERS_SECRET_PK
  PRIMARY KEY
  (APP_ID, IDEN_ID, USER_ID)
  USING INDEX PCRFMGR.XAUTH_USERS_SECRET_PK
  ENABLE VALIDATE);
  
-- XAUTH_ROLE_AGENT_USER  
CREATE TABLE PCRFMGR.XAUTH_ROLE_AGENT_USER (
	APP_ID			VARCHAR2(30 CHAR)		NOT NULL,
	IDEN_ID         VARCHAR2(20 CHAR)       NOT NULL,  
	ROLE_ID         VARCHAR2(20 CHAR)       NOT NULL,
	AGENT_APP_ID    VARCHAR2(30 CHAR)		NOT NULL,
	AGENT_IDEN_ID   VARCHAR2(20 CHAR)       NOT NULL,
	AGENT_USER_ID   VARCHAR2(30 CHAR)       NOT NULL,
	ENABLED		   	VARCHAR2(1 CHAR)		DEFAULT '1' NOT NULL,
	CRE_USER        VARCHAR2(50 CHAR)       NOT NULL,
	CRE_DATE        DATE           			NOT NULL,
	UPD_USER        VARCHAR2(50 CHAR),
	UPD_DATE        DATE
);

COMMENT ON TABLE PCRFMGR.XAUTH_ROLE_AGENT_USER IS '角色代理人資料檔';

COMMENT ON COLUMN PCRFMGR.XAUTH_ROLE_AGENT_USER.APP_ID IS '系統代號';

COMMENT ON COLUMN PCRFMGR.XAUTH_ROLE_AGENT_USER.IDEN_ID IS '識別碼';

COMMENT ON COLUMN PCRFMGR.XAUTH_ROLE_AGENT_USER.ROLE_ID IS '角色代號';

COMMENT ON COLUMN PCRFMGR.XAUTH_ROLE_AGENT_USER.AGENT_APP_ID IS '代理系統代號';

COMMENT ON COLUMN PCRFMGR.XAUTH_ROLE_AGENT_USER.AGENT_IDEN_ID IS '代理識別碼';

COMMENT ON COLUMN PCRFMGR.XAUTH_ROLE_AGENT_USER.AGENT_USER_ID IS '代理使用者帳號';

COMMENT ON COLUMN PCRFMGR.XAUTH_ROLE_AGENT_USER.ENABLED IS '是否啟用 0:停用 1:啟用';

COMMENT ON COLUMN PCRFMGR.XAUTH_ROLE_AGENT_USER.CRE_USER IS '建立人員';

COMMENT ON COLUMN PCRFMGR.XAUTH_ROLE_AGENT_USER.CRE_DATE IS '建立日期';

COMMENT ON COLUMN PCRFMGR.XAUTH_ROLE_AGENT_USER.UPD_USER IS '異動人員';

COMMENT ON COLUMN PCRFMGR.XAUTH_ROLE_AGENT_USER.UPD_DATE IS '異動日期';

CREATE UNIQUE INDEX PCRFMGR.XAUTH_ROLE_AGENT_USER_PK ON PCRFMGR.XAUTH_ROLE_AGENT_USER
(APP_ID, IDEN_ID, ROLE_ID, AGENT_APP_ID, AGENT_IDEN_ID, AGENT_USER_ID);


ALTER TABLE PCRFMGR.XAUTH_ROLE_AGENT_USER ADD (
  CONSTRAINT XAUTH_ROLE_AGENT_USER_PK
  PRIMARY KEY
  (APP_ID, IDEN_ID, ROLE_ID, AGENT_APP_ID, AGENT_IDEN_ID, AGENT_USER_ID)
  USING INDEX PCRFMGR.XAUTH_ROLE_AGENT_USER_PK
  ENABLE VALIDATE);
  
COMMIT;	