--
-- AUTHPROF  (Table) 
--
CREATE TABLE AUTHPROF
(
  SERNO          NUMBER(19)                     NOT NULL,
  AUTHID         VARCHAR2(30 CHAR)              NOT NULL,
  CREATEAGENTID  VARCHAR2(30 CHAR),
  CREATETIME     TIMESTAMP(6)                   NOT NULL,
  CREATEUSERID   VARCHAR2(30 CHAR),
  AUTHNAME       VARCHAR2(30 CHAR)              NOT NULL,
  STATUS         VARCHAR2(1 CHAR)               NOT NULL,
  SYSID          VARCHAR2(30 CHAR),
  UPDATEAGENTID  VARCHAR2(30 CHAR),
  UPDATETIME     TIMESTAMP(6)                   NOT NULL,
  UPDATEUSERID   VARCHAR2(30 CHAR),
  PRIMARY KEY
 (SERNO),
  CONSTRAINT UK_AUTHPROF
 UNIQUE (AUTHID)
);


ALTER TABLE DEPT_INFO_EXT
 DROP PRIMARY KEY CASCADE;

DROP TABLE DEPT_INFO_EXT CASCADE CONSTRAINTS;

--
-- DEPT_INFO_EXT  (Table) 
--
CREATE TABLE DEPT_INFO_EXT
(
  APP_ID     VARCHAR2(30 CHAR)                  NOT NULL,
  IDEN_ID    VARCHAR2(20 CHAR)                  NOT NULL,
  IDEN_TYPE  VARCHAR2(2 CHAR)                   DEFAULT '00'                  NOT NULL,
  CRE_USER   VARCHAR2(50 CHAR)                  NOT NULL,
  CRE_DATE   DATE                               NOT NULL,
  UPD_USER   VARCHAR2(50 CHAR),
  UPD_DATE   DATE,
  CONSTRAINT DEPT_INFO_EXT_PK
 PRIMARY KEY
 (APP_ID, IDEN_ID)
);

COMMENT ON TABLE DEPT_INFO_EXT IS '部門資料擴充檔';

COMMENT ON COLUMN DEPT_INFO_EXT.APP_ID IS '系統代號';

COMMENT ON COLUMN DEPT_INFO_EXT.IDEN_ID IS '識別碼';

COMMENT ON COLUMN DEPT_INFO_EXT.IDEN_TYPE IS '身份別 00:系統 01:通路 02:供應商';

COMMENT ON COLUMN DEPT_INFO_EXT.CRE_USER IS '建立人員';

COMMENT ON COLUMN DEPT_INFO_EXT.CRE_DATE IS '建立日期';

COMMENT ON COLUMN DEPT_INFO_EXT.UPD_USER IS '異動人員';

COMMENT ON COLUMN DEPT_INFO_EXT.UPD_DATE IS '異動日期';

--
-- DOCNOTICELOG  (Table) 
--
CREATE TABLE DOCNOTICELOG
(
  SERNO       NUMBER(19)                        NOT NULL,
  APPLYNO     VARCHAR2(30 CHAR)                 NOT NULL,
  CREATETIME  TIMESTAMP(6)                      NOT NULL,
  SERIALNO    NUMBER(10)                        NOT NULL,
  STATUS      VARCHAR2(1 CHAR)                  NOT NULL,
  SYSID       VARCHAR2(30 CHAR)                 NOT NULL,
  SYSMEMO     VARCHAR2(50 CHAR),
  UPDATETIME  TIMESTAMP(6)                      NOT NULL,
  USERID      VARCHAR2(30 CHAR)                 NOT NULL,
  PRIMARY KEY
 (SERNO)
);


ALTER TABLE DOCSTATE
 DROP PRIMARY KEY CASCADE;

DROP TABLE DOCSTATE CASCADE CONSTRAINTS;

--
-- DOCSTATE  (Table) 
--
CREATE TABLE DOCSTATE
(
  SERNO              NUMBER(19)                 NOT NULL,
  APP_ID             VARCHAR2(30 CHAR)          NOT NULL,
  APPLICANTAGENTID   VARCHAR2(30 CHAR),
  APPLYNO            VARCHAR2(30 CHAR)          NOT NULL,
  BYFLOWADMINID      VARCHAR2(30 CHAR),
  CANBATCHREVIEW     VARCHAR2(1 CHAR),
  CREATETIME         TIMESTAMP(6)               NOT NULL,
  IDEN_ID            VARCHAR2(30 CHAR)          NOT NULL,
  FLOWADMINID        VARCHAR2(30 CHAR),
  FLOWID             VARCHAR2(50 CHAR)          NOT NULL,
  FLOWSTATUS         VARCHAR2(20 CHAR)          NOT NULL,
  FLOWVERSION        VARCHAR2(10 CHAR)          NOT NULL,
  FORMID             VARCHAR2(30 CHAR),
  ISPROJROLE         VARCHAR2(1 CHAR),
  ISREVIEWDEPTROLE   VARCHAR2(1 CHAR),
  LASTREVIEWDEPTID   VARCHAR2(30 CHAR),
  LINKDESC           VARCHAR2(200 CHAR),
  LINKNAME           VARCHAR2(100 CHAR),
  MAINFORMSERNO      NUMBER(19),
  MAINFORMTABLE      VARCHAR2(50 CHAR),
  NOWTASKID          VARCHAR2(50 CHAR)          NOT NULL,
  NOWUSERID          VARCHAR2(30 CHAR),
  PARALLELPASSCOUNT  NUMBER(10),
  PREVIOUSTASKID     VARCHAR2(50 CHAR),
  PREVIOUSUSERID     VARCHAR2(30 CHAR),
  PROJID             VARCHAR2(30 CHAR),
  SERIALNO           NUMBER(10)                 NOT NULL,
  SUBFLOWDEPTID      VARCHAR2(30 CHAR),
  SUBJECT            VARCHAR2(1000 CHAR),
  SYSID              VARCHAR2(30 CHAR),
  TASKDEPTID         VARCHAR2(20 CHAR),
  TASKDESC           VARCHAR2(200 CHAR),
  TASKEXT            VARCHAR2(100 CHAR),
  TASKNAME           VARCHAR2(200 CHAR),
  TASKROLEIDS        VARCHAR2(150 CHAR),
  TASKUSERIDS        VARCHAR2(300 CHAR),
  UPDOCSTATEID       NUMBER(19),
  UPDATETIME         TIMESTAMP(6)               NOT NULL,
  APPLICANTID        VARCHAR2(255 CHAR)         NOT NULL,
  PRIMARY KEY
 (SERNO)
);


ALTER TABLE DOCSTATELOG
 DROP PRIMARY KEY CASCADE;

DROP TABLE DOCSTATELOG CASCADE CONSTRAINTS;

--
-- DOCSTATELOG  (Table) 
--
CREATE TABLE DOCSTATELOG
(
  SERNO             NUMBER(19)                  NOT NULL,
  APP_ID            VARCHAR2(30 CHAR),
  APPLYNO           VARCHAR2(30 CHAR)           NOT NULL,
  BYFLOWADMINID     VARCHAR2(30 CHAR),
  CANBATCHREVIEW    VARCHAR2(1 CHAR),
  CREATETIME        TIMESTAMP(6)                NOT NULL,
  IDEN_ID           VARCHAR2(30 CHAR),
  FLOWID            VARCHAR2(50 CHAR)           NOT NULL,
  FLOWSTATUS        VARCHAR2(20 CHAR)           NOT NULL,
  FLOWVERSION       VARCHAR2(10 CHAR)           NOT NULL,
  FROMTASKID        VARCHAR2(50 CHAR)           NOT NULL,
  ISPROJROLE        VARCHAR2(1 CHAR),
  ISREVIEWDEPTROLE  VARCHAR2(1 CHAR),
  LINKDESC          VARCHAR2(200 CHAR),
  LINKNAME          VARCHAR2(100 CHAR),
  MEMO              VARCHAR2(2000 CHAR),
  PROJID            VARCHAR2(30 CHAR),
  SERIALNO          NUMBER(10)                  NOT NULL,
  STATECREATETIME   TIMESTAMP(6),
  STATEUPDATETIME   TIMESTAMP(6),
  TASKDEPTID        VARCHAR2(30 CHAR),
  TASKDESC          VARCHAR2(200 CHAR),
  TASKEXT           VARCHAR2(100 CHAR),
  TASKNAME          VARCHAR2(100 CHAR),
  TASKROLEIDS       VARCHAR2(300 CHAR),
  TASKTYPE          VARCHAR2(20 CHAR),
  TASKUSERIDS       VARCHAR2(300 CHAR),
  TOTASKID          VARCHAR2(50 CHAR)           NOT NULL,
  AGENTID           VARCHAR2(255 CHAR)          NOT NULL,
  APPLICANTID       VARCHAR2(255 CHAR)          NOT NULL,
  BEREPRESENTEDID   VARCHAR2(255 CHAR)          NOT NULL,
  SOURCESERNO       NUMBER(19)                  NOT NULL,
  FORMID            VARCHAR2(30 CHAR)           NOT NULL,
  LASTREVIEWDEPTID  VARCHAR2(255 CHAR)          NOT NULL,
  SUBFLOWDEPTID     VARCHAR2(255 CHAR)          NOT NULL,
  USERID            VARCHAR2(255 CHAR)          NOT NULL,
  PRIMARY KEY
 (SERNO)
);

--
-- DOCTODO  (Table) 
--
CREATE TABLE DOCTODO
(
  SERNO          NUMBER(19)                     NOT NULL,
  APP_ID         VARCHAR2(30 CHAR),
  CREATEAGENTID  VARCHAR2(30 CHAR),
  CREATETIME     TIMESTAMP(6)                   NOT NULL,
  CREATEUSERID   VARCHAR2(30 CHAR),
  IDEN_ID        VARCHAR2(30 CHAR),
  FORMID         VARCHAR2(30 CHAR),
  MAINFORMSERNO  NUMBER(19),
  OLDSTATUS      VARCHAR2(1 CHAR),
  OTHERINFO      VARCHAR2(100 CHAR),
  OTHERSERNO     NUMBER(19),
  PROJID         VARCHAR2(30 CHAR),
  SERIALNO       NUMBER(10)                     NOT NULL,
  STATUS         VARCHAR2(1 CHAR)               NOT NULL,
  SUBJECT        VARCHAR2(1000 CHAR),
  SYSID          VARCHAR2(30 CHAR),
  TODONO         VARCHAR2(30 CHAR)              NOT NULL,
  UPDATEAGENTID  VARCHAR2(30 CHAR),
  UPDATETIME     TIMESTAMP(6)                   NOT NULL,
  UPDATEUSERID   VARCHAR2(30 CHAR),
  USERID         VARCHAR2(30 CHAR)              NOT NULL,
  PRIMARY KEY
 (SERNO)
);

--
-- DUTYTYPE  (Table) 
--
CREATE TABLE DUTYTYPE
(
  SERNO          NUMBER(19)                     NOT NULL,
  CREATEAGENTID  VARCHAR2(30 CHAR),
  CREATETIME     TIMESTAMP(6)                   NOT NULL,
  CREATEUSERID   VARCHAR2(30 CHAR),
  DUTYTYPEID     VARCHAR2(30 CHAR)              NOT NULL,
  DUTYTYPENAME   VARCHAR2(50 CHAR)              NOT NULL,
  STATUS         VARCHAR2(1 CHAR)               NOT NULL,
  UPDATEAGENTID  VARCHAR2(30 CHAR),
  UPDATETIME     TIMESTAMP(6)                   NOT NULL,
  UPDATEUSERID   VARCHAR2(30 CHAR),
  PRIMARY KEY
 (SERNO),
  CONSTRAINT UK_DUTYTYPE
 UNIQUE (DUTYTYPEID)
);

--
-- EMAILQUEUE  (Table) 
--
CREATE TABLE EMAILQUEUE
(
  SERNO         NUMBER(19)                      NOT NULL,
  ATTACHMENT    VARCHAR2(200 CHAR),
  CATEGORY      VARCHAR2(30 CHAR)               NOT NULL,
  CONTENT       VARCHAR2(255 CHAR),
  CREATETIME    TIMESTAMP(6)                    NOT NULL,
  CREATEUSERID  VARCHAR2(30 CHAR),
  FAILREASON    VARCHAR2(200 CHAR),
  MAILTO        VARCHAR2(1000 CHAR)             NOT NULL,
  MAILTOBCC     VARCHAR2(1000 CHAR),
  MAILTOCC      VARCHAR2(1000 CHAR),
  PRIORITY      VARCHAR2(5 CHAR)                NOT NULL,
  RETRYCNT      NUMBER(5),
  STATUS        VARCHAR2(5 CHAR)                NOT NULL,
  SUBJECT       VARCHAR2(255 CHAR)              NOT NULL,
  SYSID         VARCHAR2(30 CHAR)               NOT NULL,
  SYSMEMO       VARCHAR2(50 CHAR),
  UPDATETIME    TIMESTAMP(6)                    NOT NULL,
  UPDATEUSERID  VARCHAR2(30 CHAR),
  PRIMARY KEY
 (SERNO)
);


--
-- FLOWCONF  (Table) 
--
CREATE TABLE FLOWCONF
(
  SERNO          NUMBER(19)                     NOT NULL,
  CREATEAGENTID  VARCHAR2(30 CHAR),
  CREATETIME     TIMESTAMP(6)                   NOT NULL,
  CREATEUSERID   VARCHAR2(30 CHAR),
  FLOWDESC       VARCHAR2(50 CHAR),
  FLOWADMINID    VARCHAR2(30 CHAR),
  FLOWID         VARCHAR2(50 CHAR)              NOT NULL,
  FLOWNAME       VARCHAR2(50 CHAR)              NOT NULL,
  SYSID          VARCHAR2(30 CHAR),
  UPDATEAGENTID  VARCHAR2(30 CHAR),
  UPDATETIME     TIMESTAMP(6)                   NOT NULL,
  UPDATEUSERID   VARCHAR2(30 CHAR),
  FLOWVERSION    VARCHAR2(10 CHAR)              NOT NULL,
  PRIMARY KEY
 (SERNO),
  CONSTRAINT UK_FLOWCONF
 UNIQUE (FLOWID)
);

--
-- FLOWSTEP  (Table) 
--
CREATE TABLE FLOWSTEP
(
  SERNO              NUMBER(19)                 NOT NULL,
  CREATEAGENTID      VARCHAR2(30 CHAR),
  CREATETIME         TIMESTAMP(6)               NOT NULL,
  CREATEUSERID       VARCHAR2(30 CHAR),
  DEPTID             VARCHAR2(30 CHAR),
  STEPDESC           VARCHAR2(50 CHAR),
  DISPORD            NUMBER(10)                 NOT NULL,
  EXTENSION          VARCHAR2(100 CHAR),
  FLOWID             VARCHAR2(50 CHAR)          NOT NULL,
  ISPROJROLE         NUMBER(1)                  NOT NULL,
  ISREVIEWDEPTROLE   NUMBER(1)                  NOT NULL,
  STEPNAME           VARCHAR2(50 CHAR)          NOT NULL,
  PARALLELPASSCOUNT  NUMBER(10),
  ROLEIDS            VARCHAR2(300 CHAR),
  SAMEUSERAS         VARCHAR2(30 CHAR),
  STEPID             VARCHAR2(30 CHAR)          NOT NULL,
  STEPTYPE           VARCHAR2(10 CHAR)          NOT NULL,
  SUBFLOWID          VARCHAR2(30 CHAR),
  UPDATEAGENTID      VARCHAR2(30 CHAR),
  UPDATETIME         TIMESTAMP(6)               NOT NULL,
  UPDATEUSERID       VARCHAR2(30 CHAR),
  USERIDS            VARCHAR2(300 CHAR),
  PRIMARY KEY
 (SERNO),
  CONSTRAINT UK_FLOWSTEP
 UNIQUE (FLOWID, STEPID)
);

--
-- FLOWSTEPLINK  (Table) 
--
CREATE TABLE FLOWSTEPLINK
(
  SERNO          NUMBER(19)                     NOT NULL,
  ACTION         VARCHAR2(30 CHAR),
  CREATEAGENTID  VARCHAR2(30 CHAR),
  CREATETIME     TIMESTAMP(6)                   NOT NULL,
  CREATEUSERID   VARCHAR2(30 CHAR),
  LINKDESC       VARCHAR2(50 CHAR),
  DISPORD        NUMBER(10)                     NOT NULL,
  FLOWID         VARCHAR2(50 CHAR)              NOT NULL,
  ISCONCURRENT   NUMBER(1)                      NOT NULL,
  LINKNAME       VARCHAR2(50 CHAR)              NOT NULL,
  STEPID         VARCHAR2(30 CHAR)              NOT NULL,
  TOSTEPID       VARCHAR2(30 CHAR)              NOT NULL,
  UPDATEAGENTID  VARCHAR2(30 CHAR),
  UPDATETIME     TIMESTAMP(6)                   NOT NULL,
  UPDATEUSERID   VARCHAR2(30 CHAR),
  PRIMARY KEY
 (SERNO),
  CONSTRAINT UK_FLOWSTEPLINK
 UNIQUE (FLOWID, STEPID, TOSTEPID)
);

--
-- FLOWXML  (Table) 
--
CREATE TABLE FLOWXML
(
  SERNO          NUMBER(19)                     NOT NULL,
  CREATEAGENTID  VARCHAR2(30 CHAR),
  CREATETIME     TIMESTAMP(6)                   NOT NULL,
  CREATEUSERID   VARCHAR2(30 CHAR),
  FLOWID         VARCHAR2(50 CHAR)              NOT NULL,
  FLOWVERSION    VARCHAR2(10 CHAR)              NOT NULL,
  FLOWXML        VARCHAR2(4000 CHAR),
  SYSMEMO        VARCHAR2(50 CHAR),
  PRIMARY KEY
 (SERNO),
  CONSTRAINT UK_FLOWXML
 UNIQUE (FLOWID, FLOWVERSION)
);

--
-- FORMCONF  (Table) 
--
CREATE TABLE FORMCONF
(
  SERNO          NUMBER(19)                     NOT NULL,
  CREATEAGENTID  VARCHAR2(30 CHAR),
  CREATETIME     TIMESTAMP(6)                   NOT NULL,
  CREATEUSERID   VARCHAR2(30 CHAR),
  FORMID         VARCHAR2(30 CHAR)              NOT NULL,
  FORMURL        VARCHAR2(200 CHAR)             NOT NULL,
  FORMNAME       VARCHAR2(50 CHAR)              NOT NULL,
  SYSID          VARCHAR2(30 CHAR),
  UPDATEAGENTID  VARCHAR2(30 CHAR),
  UPDATETIME     TIMESTAMP(6)                   NOT NULL,
  UPDATEUSERID   VARCHAR2(30 CHAR),
  PRIMARY KEY
 (SERNO),
  CONSTRAINT UK_FORMCONF
 UNIQUE (FORMID)
);

--
-- HIBERNATE_SEQUENCES  (Table) 
--
CREATE TABLE HIBERNATE_SEQUENCES
(
  SEQUENCE_NAME  VARCHAR2(255 CHAR)             NOT NULL,
  NEXT_VAL       NUMBER(19),
  PRIMARY KEY
 (SEQUENCE_NAME)
);


--
-- JOBRANK  (Table) 
--
CREATE TABLE JOBRANK
(
  SERNO          NUMBER(19)                     NOT NULL,
  CREATEAGENTID  VARCHAR2(30 CHAR),
  CREATETIME     TIMESTAMP(6)                   NOT NULL,
  CREATEUSERID   VARCHAR2(30 CHAR),
  JOBRANKID      VARCHAR2(30 CHAR)              NOT NULL,
  JOBRANKNAME    VARCHAR2(50 CHAR)              NOT NULL,
  STATUS         VARCHAR2(1 CHAR)               NOT NULL,
  UPDATEAGENTID  VARCHAR2(30 CHAR),
  UPDATETIME     TIMESTAMP(6)                   NOT NULL,
  UPDATEUSERID   VARCHAR2(30 CHAR),
  PRIMARY KEY
 (SERNO),
  CONSTRAINT UK_JOBRANK
 UNIQUE (JOBRANKID)
);

--
-- JOBTITLE  (Table) 
--
CREATE TABLE JOBTITLE
(
  SERNO          NUMBER(19)                     NOT NULL,
  CREATEAGENTID  VARCHAR2(30 CHAR),
  CREATETIME     TIMESTAMP(6)                   NOT NULL,
  CREATEUSERID   VARCHAR2(30 CHAR),
  ISSUPERVISOR   VARCHAR2(255 CHAR),
  JOBTITLEID     VARCHAR2(30 CHAR)              NOT NULL,
  JOBTITLENAME   VARCHAR2(50 CHAR)              NOT NULL,
  STATUS         VARCHAR2(1 CHAR)               NOT NULL,
  UPDATEAGENTID  VARCHAR2(30 CHAR),
  UPDATETIME     TIMESTAMP(6)                   NOT NULL,
  UPDATEUSERID   VARCHAR2(30 CHAR),
  PRIMARY KEY
 (SERNO),
  CONSTRAINT UK_JOBTITLE
 UNIQUE (JOBTITLEID)
);


ALTER TABLE JOBTYPE
 DROP PRIMARY KEY CASCADE;

DROP TABLE JOBTYPE CASCADE CONSTRAINTS;

--
-- JOBTYPE  (Table) 
--
CREATE TABLE JOBTYPE
(
  SERNO          NUMBER(19)                     NOT NULL,
  CREATEAGENTID  VARCHAR2(30 CHAR),
  CREATETIME     TIMESTAMP(6)                   NOT NULL,
  CREATEUSERID   VARCHAR2(30 CHAR),
  JOBTYPEID      VARCHAR2(30 CHAR)              NOT NULL,
  JOBTYPENAME    VARCHAR2(50 CHAR)              NOT NULL,
  STATUS         VARCHAR2(1 CHAR)               NOT NULL,
  UPDATEAGENTID  VARCHAR2(30 CHAR),
  UPDATETIME     TIMESTAMP(6)                   NOT NULL,
  UPDATEUSERID   VARCHAR2(30 CHAR),
  PRIMARY KEY
 (SERNO),
  CONSTRAINT UK_JOBTYPE
 UNIQUE (JOBTYPEID)
);
--
-- PROJAUTH  (Table) 
--
CREATE TABLE PROJAUTH
(
  PROJID  VARCHAR2(30 CHAR)                     NOT NULL,
  AUTHID  VARCHAR2(30 CHAR)                     NOT NULL,
  PRIMARY KEY
 (PROJID, AUTHID)
);


ALTER TABLE PROJPROF
 DROP PRIMARY KEY CASCADE;

DROP TABLE PROJPROF CASCADE CONSTRAINTS;

--
-- PROJPROF  (Table) 
--
CREATE TABLE PROJPROF
(
  SERNO          NUMBER(19)                     NOT NULL,
  CREATEAGENTID  VARCHAR2(30 CHAR),
  CREATETIME     TIMESTAMP(6)                   NOT NULL,
  CREATEUSERID   VARCHAR2(30 CHAR),
  PROJNAME       VARCHAR2(300 CHAR)             NOT NULL,
  PROJID         VARCHAR2(30 CHAR)              NOT NULL,
  STATUS         VARCHAR2(1 CHAR)               NOT NULL,
  SYSID          VARCHAR2(30 CHAR),
  UPDATEAGENTID  VARCHAR2(30 CHAR),
  UPDATETIME     TIMESTAMP(6)                   NOT NULL,
  UPDATEUSERID   VARCHAR2(30 CHAR),
  PRIMARY KEY
 (SERNO),
  CONSTRAINT UK_PROJPROF
 UNIQUE (PROJID)
);


ALTER TABLE SUBFLOWCONF
 DROP PRIMARY KEY CASCADE;

DROP TABLE SUBFLOWCONF CASCADE CONSTRAINTS;

--
-- SUBFLOWCONF  (Table) 
--
CREATE TABLE SUBFLOWCONF
(
  SERNO          NUMBER(19)                     NOT NULL,
  CREATEAGENTID  VARCHAR2(30 CHAR),
  CREATETIME     TIMESTAMP(6)                   NOT NULL,
  CREATEUSERID   VARCHAR2(30 CHAR),
  SUBFLOWDESC    VARCHAR2(50 CHAR),
  FINISHTO       VARCHAR2(30 CHAR)              NOT NULL,
  FLOWID         VARCHAR2(50 CHAR)              NOT NULL,
  SUBFLOWNAME    VARCHAR2(50 CHAR)              NOT NULL,
  RETURNTO       VARCHAR2(30 CHAR)              NOT NULL,
  SUBFLOWID      VARCHAR2(50 CHAR)              NOT NULL,
  UPDATEAGENTID  VARCHAR2(30 CHAR),
  UPDATETIME     TIMESTAMP(6)                   NOT NULL,
  UPDATEUSERID   VARCHAR2(30 CHAR),
  PRIMARY KEY
 (SERNO),
  CONSTRAINT UK_SUBFLOWCONF
 UNIQUE (FLOWID, SUBFLOWID),
  CONSTRAINT UK2_SUBFLOWCONF
 UNIQUE (SUBFLOWID)
);


ALTER TABLE SUBJOBTYPE
 DROP PRIMARY KEY CASCADE;

DROP TABLE SUBJOBTYPE CASCADE CONSTRAINTS;

--
-- SUBJOBTYPE  (Table) 
--
CREATE TABLE SUBJOBTYPE
(
  SERNO           NUMBER(19)                    NOT NULL,
  CREATEAGENTID   VARCHAR2(30 CHAR),
  CREATETIME      TIMESTAMP(6)                  NOT NULL,
  CREATEUSERID    VARCHAR2(30 CHAR),
  JOBTYPEID       VARCHAR2(30 CHAR)             NOT NULL,
  STATUS          VARCHAR2(1 CHAR)              NOT NULL,
  SUBJOBTYPEID    VARCHAR2(30 CHAR)             NOT NULL,
  SUBJOBTYPENAME  VARCHAR2(50 CHAR)             NOT NULL,
  UPDATEAGENTID   VARCHAR2(30 CHAR),
  UPDATETIME      TIMESTAMP(6)                  NOT NULL,
  UPDATEUSERID    VARCHAR2(30 CHAR),
  PRIMARY KEY
 (SERNO),
  CONSTRAINT UK_SUBJOBTYPE
 UNIQUE (SUBJOBTYPEID)
);


ALTER TABLE SYSPROF
 DROP PRIMARY KEY CASCADE;

DROP TABLE SYSPROF CASCADE CONSTRAINTS;

--
-- SYSPROF  (Table) 
--
CREATE TABLE SYSPROF
(
  SYSID          VARCHAR2(30 CHAR)              NOT NULL,
  CREATEAGENTID  VARCHAR2(30 CHAR),
  CREATETIME     TIMESTAMP(6)                   NOT NULL,
  CREATEUSERID   VARCHAR2(30 CHAR),
  SYSNAME        VARCHAR2(30 CHAR)              NOT NULL,
  STATUS         VARCHAR2(1 CHAR)               NOT NULL,
  UPDATEAGENTID  VARCHAR2(30 CHAR),
  UPDATETIME     TIMESTAMP(6)                   NOT NULL,
  UPDATEUSERID   VARCHAR2(30 CHAR),
  PRIMARY KEY
 (SYSID)
);


ALTER TABLE TRAININGORG
 DROP PRIMARY KEY CASCADE;

DROP TABLE TRAININGORG CASCADE CONSTRAINTS;

--
-- TRAININGORG  (Table) 
--
CREATE TABLE TRAININGORG
(
  SERNO            NUMBER(19)                   NOT NULL,
  CREATEAGENTID    VARCHAR2(30 CHAR),
  CREATETIME       TIMESTAMP(6)                 NOT NULL,
  CREATEUSERID     VARCHAR2(30 CHAR),
  STATUS           VARCHAR2(1 CHAR)             NOT NULL,
  TRAININGORGID    VARCHAR2(30 CHAR)            NOT NULL,
  TRAININGORGNAME  VARCHAR2(100 CHAR)           NOT NULL,
  UPDATEAGENTID    VARCHAR2(30 CHAR),
  UPDATETIME       TIMESTAMP(6)                 NOT NULL,
  UPDATEUSERID     VARCHAR2(30 CHAR),
  PRIMARY KEY
 (SERNO),
  CONSTRAINT UK_TRAININGORG
 UNIQUE (TRAININGORGID)
);
